apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggue
  template:
    metadata:
      labels:
        app: ggue
    spec:
      containers:
      - image: okteto.dev/ray:ggue
        name: ggue
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "66abf5bb-1b6a-4305-b250-023029e48b94"
        - name: Vless_Path
          value: "/ray"
        - name: Vmess_UUID
          value: "66abf5bb-1b6a-4305-b250-023029e48b94"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
